const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('axiom', {
  scratchInfo: () => ipcRenderer.invoke('scratch:info'),
  scratchPower: (op, args = {}) => ipcRenderer.invoke('scratch:power', op, args),
  openScratchExtensionJs: () => ipcRenderer.invoke('scratch:openExtensionJs'),
  confirmScratchDiscard: () => ipcRenderer.sendSync('scratch:confirmDiscard'),
  openScratchSb3: path => ipcRenderer.invoke('scratch:openSb3', path),
  saveScratchSb3: data => ipcRenderer.invoke('scratch:saveSb3', data),
  openScratch: () => ipcRenderer.invoke('scratch:open'),
  saveScratch: data => ipcRenderer.invoke('scratch:save', data),
  openWorkspace: () => ipcRenderer.invoke('workspace:open'),
  refreshWorkspace: root => ipcRenderer.invoke('workspace:refresh', root),
  restoreWorkspace: () => ipcRenderer.invoke('workspace:restore'),
  recentWorkspaces: () => ipcRenderer.invoke('workspace:recent'),
  openWorkspacePath: root => ipcRenderer.invoke('workspace:openPath', root),
  openFiles: root => ipcRenderer.invoke('file:openDialog', root),
  searchWorkspace: (root, query, options = {}) => ipcRenderer.invoke('workspace:search', root, query, options),
  replaceWorkspace: (root, query, replacement, options = {}) => ipcRenderer.invoke('workspace:replace', root, query, replacement, options),
  getIconManifest: () => ipcRenderer.invoke('icons:manifest'),
  readFile: p => ipcRenderer.invoke('file:read', p),
  readFileOptional: p => ipcRenderer.invoke('file:readOptional', p),
  writeFile: (p, content) => ipcRenderer.invoke('file:write', p, content),
  createFile: (p, isDir = false) => ipcRenderer.invoke('file:create', p, isDir),
  renameFile: (from, to) => ipcRenderer.invoke('file:rename', from, to),
  deleteFile: p => ipcRenderer.invoke('file:delete', p),
  runTerminal: (command, cwd) => ipcRenderer.invoke('terminal:run', command, cwd),
  createTerminal: (shell, cwd) => ipcRenderer.invoke('terminal:create', {shell,cwd}),
  writeTerminal: (id, data) => ipcRenderer.invoke('terminal:write', id, data),
  resizeTerminal: (id, cols, rows) => ipcRenderer.invoke('terminal:resize', id, cols, rows),
  killTerminal: id => ipcRenderer.invoke('terminal:kill', id),
  onTerminalData: cb => ipcRenderer.on('terminal:data', (_e, data) => cb(data)),
  onTerminalExit: cb => ipcRenderer.on('terminal:exit', (_e, data) => cb(data)),
  gitStatus: cwd => ipcRenderer.invoke('git:status', cwd),
  gitChanges: cwd => ipcRenderer.invoke('git:changes', cwd),
  gitAddAll: cwd => ipcRenderer.invoke('git:addAll', cwd),
  gitCommit: (cwd, message) => ipcRenderer.invoke('git:commit', cwd, message),
  gitStageFile: (cwd, file) => ipcRenderer.invoke('git:stageFile', cwd, file),
  gitUnstageFile: (cwd, file) => ipcRenderer.invoke('git:unstageFile', cwd, file),
  gitDiscardFile: (cwd, file) => ipcRenderer.invoke('git:discardFile', cwd, file),
  gitBranches: cwd => ipcRenderer.invoke('git:branches', cwd),
  gitCheckout: (cwd, branch) => ipcRenderer.invoke('git:checkout', cwd, branch),
  gitShowHead: (cwd, file) => ipcRenderer.invoke('git:showHead', cwd, file),
  appInfo: () => ipcRenderer.invoke('app:info'),
  checkForUpdates: () => ipcRenderer.invoke('app:update:check'),
  installUpdate: () => ipcRenderer.invoke('app:update:install'),
  onUpdateProgress: cb => ipcRenderer.on('app:update:progress', (_e, data) => cb(data)),
  getConfig: () => ipcRenderer.invoke('config:getAll'),
  getConfigDefaults: () => ipcRenderer.invoke('config:getDefaults'),
  getConfigValue: key => ipcRenderer.invoke('config:get', key),
  setConfigValue: (key, value) => ipcRenderer.invoke('config:set', key, value),
  setConfigValues: values => ipcRenderer.invoke('config:setMany', values),
  reloadConfig: () => ipcRenderer.invoke('config:reload'),
  resetConfig: () => ipcRenderer.invoke('config:reset'),
  getConfigPath: () => ipcRenderer.invoke('config:path'),
  getPreferenceResource: name => ipcRenderer.invoke('preferences:resource', name),
  exportPreferences: () => ipcRenderer.invoke('preferences:export'),
  importPreferences: () => ipcRenderer.invoke('preferences:import'),
  listExtensions: () => ipcRenderer.invoke('extensions:list'),
  getMarketplace: (force = false) => ipcRenderer.invoke('extensions:marketplace', force),
  updateExtension: id => ipcRenderer.invoke('extensions:update', id),
  installExtension: id => ipcRenderer.invoke('extensions:install', id),
  uninstallExtension: id => ipcRenderer.invoke('extensions:uninstall', id),
  openExtensionsFolder: () => ipcRenderer.invoke('extensions:openFolder'),
  readExtensionText: (id, relativePath) => ipcRenderer.invoke('extensions:readText', id, relativePath),
  extensionNetworkRequest: (id, request) => ipcRenderer.invoke('extensions:networkRequest', id, request),
  describeRunner: path => ipcRenderer.invoke('runner:describe', path),
  prepareRunner: path => ipcRenderer.invoke('runner:prepare', path),
  onWorkspaceFileChanged: cb => ipcRenderer.on('workspace:fileChanged', (_e, data) => cb(data)),
  reveal: p => ipcRenderer.invoke('system:reveal', p),
  clipboardWrite: text => ipcRenderer.invoke('system:clipboardWrite', text),
  openExternal: url => ipcRenderer.invoke('system:openExternal', url),
  rendererReady: info => ipcRenderer.send('renderer:ready', info)
});
